# Generated by Django 5.2.14 on 2026-05-25 23:38

import django.db.models.deletion
import rides.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('rider', 'Rider'), ('support', 'Support')], default='rider', max_length=32)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id_user'],
            },
            managers=[
                ('objects', rides.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField(db_index=True)),
                ('driver', models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(db_column='id_rider', on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ride',
                'ordering': ['pickup_time', 'id_ride'],
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id_ride_event', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('ride', models.ForeignKey(db_column='id_ride', on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='rides.ride')),
            ],
            options={
                'db_table': 'ride_event',
                'ordering': ['created_at', 'id_ride_event'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'pickup_time'], name='ride_status_03df0b_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_pickup__112ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', 'pickup_time'], name='ride_id_ride_c7f39e_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'pickup_time'], name='ride_id_driv_b3b9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['ride', 'created_at'], name='ride_event_id_ride_ca7133_idx'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['created_at'], name='ride_event_created_fda889_idx'),
        ),
    ]
